<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[3]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[4]=array(3,1,1,'6LWE6LSo5Luj5Yqe');
$cfg_Cs[5]=array(3,1,1,'6LWE6LSo5qCH5YeG');
$cfg_Cs[6]=array(3,1,1,'5a6J5YWo6K645Y+v');
$cfg_Cs[8]=array(2,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[9]=array(2,1,1,'6KGM5Lia5Yqo5oCB');
$cfg_Cs[10]=array(2,1,1,'6KGM5Lia55+l6K+G');
$cfg_Cs[11]=array(0,1,1,'5pyN5Yqh5Lit5b+D');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[13]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[16]=array(13,1,1,'5Y+R5bGV5Y6G56iL');
$cfg_Cs[17]=array(13,1,1,'5Zui6Zif5Lq65ZGY');
$cfg_Cs[18]=array(3,1,1,'5qGI5L6L5bGV56S6');
?>