<div class="media feature-item">
                                            <div class="media-left feature-img"><img src="[field:picname/]" alt="[field:fulltitle/]"/></div>
                                            <div class="media-right media-middle feature-info"><a href="[field:arcurl/]" class="media-heading feature-title">[field:title/]</a>

                                                <div class="info"><a href="[field:arcurl/]" class="category">栏目: <span> [field:typename/]</span></a></div>
                                                <div class="info"><a href="[field:arcurl/]" class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</a></div>
                                            </div>
                                        </div>