<div class="col-md-4 col-xs-6">
                      <div class="sunhouse-item"><a class="wrapper-image" href="[field:arcurl/]"><img class="img-responsive layout-1" src="[field:picname/]" alt="[field:fulltitle/]"><img class="img-responsive layout-2" src="/skin/images/skin.png" alt="[field:fulltitle/]">
                        <div class="note for-sale">
                          <p>[field:pubdate function="MyDate('d',@me)"/]<br>
                            [field:pubdate function="MyDate('M',@me)"/]</p>
                        </div>
                        </a>
                        <div class="wrapper-content">
                          <div class="about-house"><a class="title" href="[field:arcurl/]">[field:title/]</a>
                            <p class="text">[field:infos/]...</p>
                          </div>
                        </div>
                      </div>
                    </div>