<div class="sunhouse-item">
                                    <div class="wrapper-image"><img src="[field:picname/]" alt="[field:fulltitle/]" class="img-responsive"/>

                                        <div class="note for-sale"><p><span>[field:pubdate function="MyDate('d',@me)"/]</span> [field:pubdate function="MyDate('M',@me)"/]</p></div>
                                    </div>
                                    <div class="wrapper-content">
                                      
                                        <div class="about-house"><a href="[field:arcurl/]" class="title">[field:title/]</a>

                                            <p class="text">[field:infos/]...</p><a href="[field:arcurl/]" class="btn btn-blue">查看详情</a></div>
                                    </div>
                                </div>