<?php
$z[0]=Array("arcurl","",78,93);
$z[0][4]=array();
$z[1]=Array("picname","",123,139);
$z[1][4]=array();
$z[2]=Array("fulltitle","",146,164);
$z[2][4]=array();
$z[3]=Array("arcurl","",237,252);
$z[3][4]=array();
$z[4]=Array("title","",268,282);
$z[4][4]=array();
$z[5]=Array("arcurl","",402,417);
$z[5][4]=array();
$z[6]=Array("pubdate","",432,479);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>