<div class="media">
                        <div class="media-left"><a href="[field:arcurl/]" class="img-hover"><img src="[field:picname/]" alt="[field:fulltitle/]"/></a></div>
                        <div class="media-right"><a href="[field:arcurl/]" class="title">[field:title/]</a>
                          <div class="info">
                            <div class="date-created item"><a href="[field:arcurl/]" class="text">[field:pubdate function="MyDate('Y-m-d',@me)"/]</a></div>
                          </div>
                        </div>
                      </div>