<?php
$z[0]=Array("arclist","\r\n                      <div class=\"media\">\r\n                        <div class=\"media-left\"><a href=\"[field:arcurl/]\" class=\"img-hover\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\"/></a></div>\r\n                        <div class=\"media-right\"><a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a>\r\n                          <div class=\"info\">\r\n                            <div class=\"date-created item\"><a href=\"[field:arcurl/]\" class=\"text\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</a></div>\r\n                          </div>\r\n                        </div>\r\n                      </div>\r\n                      ",3084,3793);
$z[0][4]=array();
$z[0][4]['titlelen']="30";
$z[0][4]['row']="3";
$z[0][4]['typeid']="3";
$z[0][4]['infolen']="50";
$z[1]=Array("arclist"," <a href=\"[field:arcurl/]\" class=\"thumb img-hover\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" class=\"img-responsive\" width=\"90\" height=\"60\" style=\"height:60px; width:90px;\"/></a> ",4172,4437);
$z[1][4]=array();
$z[1][4]['titlelen']="20";
$z[1][4]['row']="9";
$z[1][4]['typeid']="3";
$z[1][4]['infolen']="50";
$z[2]=Array("global","",4768,4794);
$z[2][4]=array();
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",4860,4884);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";

?>